// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cqmgmtwglyfraiuxcixd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNxbWdtdHdnbHlmcmFpdXhjaXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MjgyNzMsImV4cCI6MjA2MTAwNDI3M30.pEuYFsKNyU-PJYBykNQBR_xkiM-M7Vmaq1S7xG9wzpU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);